/* ============================================================
   data.js — YKS konu havuzu + kaynak eşlemesi
   ------------------------------------------------------------
   Bu dosya SADECE veri içerir. Mantık app.js'te.
   Her ders bir "track" (öncelik sırasına göre p1..p4).
   Her track'in topics dizisi sıralıdır: konu anlatımı önce,
   biten konunun soru bankası bloğu hemen ardından gelir.
   "src" alanı kullanıcının ELİNDE OLAN kitaplara karşılık gelir
   (mesajında belirttiği listeden).
   ============================================================ */

const SOURCES = {
  // konu anlatım föyleri
  aytMatAnlatim:  "AYT Matematik konu anlatım föyleri (Limit)",
  aytKimyaAnlatim:"AYT Kimya konu anlatım föyleri (Limit)",
  aytFizikAnlatim:"AYT Fizik konu anlatım föyleri (Limit)",
  aytTytBiyoAnlatim:"AYT-TYT Biyoloji konu anlatım föyleri (Limit)",
  tytMat1Anlatim: "TYT Temel Matematik 1. kitap (Limit)",
  tytMat2Anlatim: "TYT Temel Matematik 2. kitap (Limit)",
  geoAnlatim:     "TYT-AYT Geometri konu anlatım föyleri (Limit)",
  // soru bankaları
  tytKimyaBank:   "TYT Kimya soru bankası (Limit)",
  aytKimyaBank:   "AYT Kimya soru bankası (Limit)",
  aytFizikBank:   "AYT Fizik soru bankası (Limit)",
  geoBank:        "TYT-AYT Geometri soru bankası (Limit)",
  aytMatBank:     "AYT Matematik soru bankası (Limit)",
  tytAytBiyoBank: "TYT-AYT Biyoloji soru bankası (Limit)",
  tytTurkceBank:  "TYT Türkçe konu özetli soru bankası (Optik)",
  tytAytTarihBank:"TYT-AYT Tarih konu özetli soru bankası (Optik)",
  tytCografyaBank:"TYT Coğrafya konu özetli soru bankası (Optik)",
  tytMat4k:       "TYT Matematik konu özetli soru bankası (4K)",
  tytTurkce4k:    "TYT Türkçe konu özetli soru bankası (4K)",
  tytTarih4k:     "TYT Tarih konu özetli soru bankası (4K)",
  tytCografya4k:  "TYT Coğrafya konu özetli soru bankası (4K)",
  tytMatIlyas:    "TYT Matematik — İlyas Güneş Benim Hocam",
  tytAytFizikElKitabi:"TYT-AYT Fizik el kitabı (Limit, 2025)",
  tytAytTarihElKitabi:"TYT-AYT Tarih el kitabı (Limit, 2025)",
  none: null
};

const TRACKS = [
  {
    id: "p1",
    label: "Matematik & Fizik",
    priority: 1,
    color: "p1",
    weight: 4,
    topics: [
      { id:"m01", name:"Sayı Basamakları", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m02", name:"Sayı Basamakları - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m03", name:"Rasyonel Sayılar", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m04", name:"Rasyonel Sayılar - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m05", name:"Basit Eşitsizlikler", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m06", name:"Basit Eşitsizlikler - Soru", type:"soru", src:"tytMat4k", qCount:40 },
      { id:"m07", name:"Mutlak Değer", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m08", name:"Mutlak Değer - Soru", type:"soru", src:"tytMat4k", qCount:40 },
      { id:"m09", name:"Üslü Sayılar", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m10", name:"Üslü Sayılar - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m11", name:"Köklü Sayılar", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m12", name:"Köklü Sayılar - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m13", name:"Çarpanlara Ayırma", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m14", name:"Çarpanlara Ayırma - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m15", name:"Oran Orantı", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m16", name:"Oran Orantı - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m17", name:"Problemler (Sayı, Yaş)", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m18", name:"Sayı-Yaş Problemleri - Soru", type:"soru", src:"tytMatIlyas", qCount:50 },
      { id:"m19", name:"Problemler (Kar-Zarar, Yüzde)", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m20", name:"Kar-Zarar/Yüzde - Soru", type:"soru", src:"tytMatIlyas", qCount:50 },
      { id:"m21", name:"Problemler (Hareket-Hız)", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m22", name:"Hareket-Hız - Soru", type:"soru", src:"tytMatIlyas", qCount:50 },
      { id:"m23", name:"Problemler (İşçi-Havuz, Karışım)", type:"anlatim", src:"tytMat1Anlatim" },
      { id:"m24", name:"İşçi-Havuz/Karışım - Soru", type:"soru", src:"tytMatIlyas", qCount:50 },
      { id:"m25", name:"Kümeler", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m26", name:"Kümeler - Soru", type:"soru", src:"tytMat4k", qCount:40 },
      { id:"m27", name:"Mantık", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m28", name:"Mantık - Soru", type:"soru", src:"tytMat4k", qCount:40 },
      { id:"m29", name:"Fonksiyonlar", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m30", name:"Fonksiyonlar - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m31", name:"Polinomlar", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m32", name:"Polinomlar - Soru", type:"soru", src:"tytMat4k", qCount:40 },
      { id:"m33", name:"2. Derece Denklemler", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m34", name:"2. Derece Denklemler - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m35", name:"Permütasyon-Kombinasyon", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m36", name:"Permütasyon-Kombinasyon - Soru", type:"soru", src:"tytMat4k", qCount:50 },
      { id:"m37", name:"Olasılık", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m38", name:"Olasılık - Soru", type:"soru", src:"tytMat4k", qCount:40 },
      { id:"m39", name:"Veri - İstatistik", type:"anlatim", src:"tytMat2Anlatim" },
      { id:"m40", name:"Veri - Soru", type:"soru", src:"tytMat4k", qCount:30 },
      { id:"g01", name:"Doğruda Açılar", type:"anlatim", src:"geoAnlatim" },
      { id:"g02", name:"Doğruda Açılar - Soru", type:"soru", src:"geoBank", qCount:40 },
      { id:"g03", name:"Üçgende Açı", type:"anlatim", src:"geoAnlatim" },
      { id:"g04", name:"Üçgende Açı - Soru", type:"soru", src:"geoBank", qCount:50 },
      { id:"g05", name:"Üçgende Alan", type:"anlatim", src:"geoAnlatim" },
      { id:"g06", name:"Üçgende Alan - Soru", type:"soru", src:"geoBank", qCount:50 },
      { id:"g07", name:"Özel Üçgenler", type:"anlatim", src:"geoAnlatim" },
      { id:"g08", name:"Özel Üçgenler - Soru", type:"soru", src:"geoBank", qCount:50 },
      { id:"g09", name:"Çokgenler", type:"anlatim", src:"geoAnlatim" },
      { id:"g10", name:"Çokgenler - Soru", type:"soru", src:"geoBank", qCount:40 },
      { id:"g11", name:"Dörtgenler", type:"anlatim", src:"geoAnlatim" },
      { id:"g12", name:"Dörtgenler - Soru", type:"soru", src:"geoBank", qCount:50 },
      { id:"g13", name:"Çember ve Daire", type:"anlatim", src:"geoAnlatim" },
      { id:"g14", name:"Çember ve Daire - Soru", type:"soru", src:"geoBank", qCount:50 },
      { id:"g15", name:"Katı Cisimler", type:"anlatim", src:"geoAnlatim" },
      { id:"g16", name:"Katı Cisimler - Soru", type:"soru", src:"geoBank", qCount:40 },
      { id:"g17", name:"Analitik Geometri", type:"anlatim", src:"geoAnlatim" },
      { id:"g18", name:"Analitik Geometri - Soru", type:"soru", src:"geoBank", qCount:40 },
      { id:"a01", name:"Fonksiyonlar (AYT)", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a02", name:"Fonksiyonlar (AYT) - Soru", type:"soru", src:"aytMatBank", qCount:40 },
      { id:"a03", name:"Polinomlar (AYT)", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a04", name:"Polinomlar (AYT) - Soru", type:"soru", src:"aytMatBank", qCount:40 },
      { id:"a05", name:"2.Derece Denklemler (AYT)", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a06", name:"2.Derece Denklemler - Soru", type:"soru", src:"aytMatBank", qCount:40 },
      { id:"a07", name:"Eşitsizlikler (AYT)", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a08", name:"Eşitsizlikler - Soru", type:"soru", src:"aytMatBank", qCount:30 },
      { id:"a09", name:"Trigonometri", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a10", name:"Trigonometri - Soru", type:"soru", src:"aytMatBank", qCount:50 },
      { id:"a11", name:"Logaritma", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a12", name:"Logaritma - Soru", type:"soru", src:"aytMatBank", qCount:50 },
      { id:"a13", name:"Diziler", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a14", name:"Diziler - Soru", type:"soru", src:"aytMatBank", qCount:40 },
      { id:"a15", name:"Limit ve Süreklilik", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a16", name:"Limit ve Süreklilik - Soru", type:"soru", src:"aytMatBank", qCount:50 },
      { id:"a17", name:"Türev", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a18", name:"Türev - Soru", type:"soru", src:"aytMatBank", qCount:60 },
      { id:"a19", name:"İntegral", type:"anlatim", src:"aytMatAnlatim" },
      { id:"a20", name:"İntegral - Soru", type:"soru", src:"aytMatBank", qCount:60 },
      { id:"f01", name:"Fizik Bilimine Giriş", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f02", name:"Madde ve Özellikleri", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f03", name:"Madde ve Özellikleri - Soru", type:"soru", src:"none", qCount:30 },
      { id:"f04", name:"Hareket", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f05", name:"Hareket - Soru", type:"soru", src:"none", qCount:40 },
      { id:"f06", name:"Kuvvet ve Hareket", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f07", name:"Kuvvet ve Hareket - Soru", type:"soru", src:"none", qCount:40 },
      { id:"f08", name:"İş, Güç, Enerji", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f09", name:"İş Güç Enerji - Soru", type:"soru", src:"none", qCount:40 },
      { id:"f10", name:"Isı ve Sıcaklık", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f11", name:"Isı ve Sıcaklık - Soru", type:"soru", src:"none", qCount:30 },
      { id:"f12", name:"Elektrik", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f13", name:"Elektrik - Soru", type:"soru", src:"none", qCount:40 },
      { id:"f14", name:"Manyetizma", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f15", name:"Manyetizma - Soru", type:"soru", src:"none", qCount:30 },
      { id:"f16", name:"Basınç ve Kaldırma Kuvveti", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f17", name:"Basınç - Soru", type:"soru", src:"none", qCount:30 },
      { id:"f18", name:"Optik", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f19", name:"Optik - Soru", type:"soru", src:"none", qCount:30 },
      { id:"f20", name:"Dalgalar", type:"anlatim", src:"tytAytFizikElKitabi" },
      { id:"f21", name:"Dalgalar - Soru", type:"soru", src:"none", qCount:30 },
      { id:"af01", name:"Vektörler", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af02", name:"Vektörler - Soru", type:"soru", src:"aytFizikBank", qCount:30 },
      { id:"af03", name:"Bağıl Hareket", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af04", name:"Bağıl Hareket - Soru", type:"soru", src:"aytFizikBank", qCount:30 },
      { id:"af05", name:"Newton'un Hareket Yasaları", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af06", name:"Newton Yasaları - Soru", type:"soru", src:"aytFizikBank", qCount:40 },
      { id:"af07", name:"İtme ve Momentum", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af08", name:"İtme-Momentum - Soru", type:"soru", src:"aytFizikBank", qCount:40 },
      { id:"af09", name:"Tork ve Denge", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af10", name:"Tork-Denge - Soru", type:"soru", src:"aytFizikBank", qCount:30 },
      { id:"af11", name:"Bağımlı Hareketler", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af12", name:"Bağımlı Hareketler - Soru", type:"soru", src:"aytFizikBank", qCount:30 },
      { id:"af13", name:"Basit Harmonik Hareket", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af14", name:"Basit Harmonik Hareket - Soru", type:"soru", src:"aytFizikBank", qCount:40 },
      { id:"af15", name:"Elektrik Alan ve Potansiyel", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af16", name:"Elektrik Alan - Soru", type:"soru", src:"aytFizikBank", qCount:40 },
      { id:"af17", name:"Manyetik Alan", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af18", name:"Manyetik Alan - Soru", type:"soru", src:"aytFizikBank", qCount:40 },
      { id:"af19", name:"Atom Fiziği ve Radyoaktivite", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af20", name:"Atom-Radyoaktivite - Soru", type:"soru", src:"aytFizikBank", qCount:30 },
      { id:"af21", name:"Modern Fizik", type:"anlatim", src:"aytFizikAnlatim" },
      { id:"af22", name:"Modern Fizik - Soru", type:"soru", src:"aytFizikBank", qCount:30 }
    ]
  },
  {
    id: "p2",
    label: "Kimya & Biyoloji",
    priority: 2,
    color: "p2",
    weight: 3,
    topics: [
      { id:"k01", name:"Kimya Bilimi", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k02", name:"Kimya Bilimi - Soru", type:"soru", src:"tytKimyaBank", qCount:30 },
      { id:"k03", name:"Atom ve Periyodik Sistem", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k04", name:"Atom ve Periyodik Sistem - Soru", type:"soru", src:"tytKimyaBank", qCount:40 },
      { id:"k05", name:"Kimyasal Türler Arası Etkileşim", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k06", name:"Kimyasal Türler - Soru", type:"soru", src:"tytKimyaBank", qCount:40 },
      { id:"k07", name:"Maddenin Halleri", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k08", name:"Maddenin Halleri - Soru", type:"soru", src:"tytKimyaBank", qCount:30 },
      { id:"k09", name:"Doğa ve Kimya", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k10", name:"Doğa ve Kimya - Soru", type:"soru", src:"tytKimyaBank", qCount:20 },
      { id:"k11", name:"Kimyanın Temel Kanunları", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k12", name:"Kimyanın Temel Kanunları - Soru", type:"soru", src:"tytKimyaBank", qCount:30 },
      { id:"k13", name:"Mol Kavramı", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k14", name:"Mol Kavramı - Soru", type:"soru", src:"tytKimyaBank", qCount:40 },
      { id:"k15", name:"Karışımlar", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k16", name:"Karışımlar - Soru", type:"soru", src:"tytKimyaBank", qCount:30 },
      { id:"k17", name:"Asit-Baz-Tuz", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k18", name:"Asit-Baz-Tuz - Soru", type:"soru", src:"tytKimyaBank", qCount:40 },
      { id:"k19", name:"Kimya Her Yerde", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k20", name:"Kimya Her Yerde - Soru", type:"soru", src:"tytKimyaBank", qCount:20 },
      { id:"k21", name:"Modern Atom Teorisi (AYT)", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k22", name:"Modern Atom Teorisi - Soru", type:"soru", src:"aytKimyaBank", qCount:30 },
      { id:"k23", name:"Gazlar", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k24", name:"Gazlar - Soru", type:"soru", src:"aytKimyaBank", qCount:40 },
      { id:"k25", name:"Sıvı Çözeltiler", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k26", name:"Sıvı Çözeltiler - Soru", type:"soru", src:"aytKimyaBank", qCount:40 },
      { id:"k27", name:"Kimyasal Tepkimelerde Enerji", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k28", name:"Tepkimelerde Enerji - Soru", type:"soru", src:"aytKimyaBank", qCount:30 },
      { id:"k29", name:"Kimyasal Tepkimelerde Hız", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k30", name:"Tepkimelerde Hız - Soru", type:"soru", src:"aytKimyaBank", qCount:30 },
      { id:"k31", name:"Kimyasal Denge", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k32", name:"Kimyasal Denge - Soru", type:"soru", src:"aytKimyaBank", qCount:40 },
      { id:"k33", name:"Asit-Baz Dengesi (AYT)", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k34", name:"Asit-Baz Dengesi - Soru", type:"soru", src:"aytKimyaBank", qCount:40 },
      { id:"k35", name:"Çözünürlük Dengesi", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k36", name:"Çözünürlük Dengesi - Soru", type:"soru", src:"aytKimyaBank", qCount:30 },
      { id:"k37", name:"Elektrokimya", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k38", name:"Elektrokimya - Soru", type:"soru", src:"aytKimyaBank", qCount:30 },
      { id:"k39", name:"Organik Kimyaya Giriş", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k40", name:"Organik Kimyaya Giriş - Soru", type:"soru", src:"aytKimyaBank", qCount:30 },
      { id:"k41", name:"Organik Kimya (Hidrokarbonlar vs.)", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k42", name:"Organik Kimya - Soru", type:"soru", src:"aytKimyaBank", qCount:40 },
      { id:"k43", name:"Enerji Kaynakları ve Bilimsel Gelişmeler", type:"anlatim", src:"aytKimyaAnlatim" },
      { id:"k44", name:"Enerji Kaynakları - Soru", type:"soru", src:"aytKimyaBank", qCount:20 },
      { id:"b01", name:"Canlıların Ortak Özellikleri", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b02", name:"Canlıların Ortak Özellikleri - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b03", name:"Hücre", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b04", name:"Hücre - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b05", name:"Canlıların Sınıflandırılması", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b06", name:"Sınıflandırma - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b07", name:"Hücre Bölünmeleri (Mitoz-Mayoz)", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b08", name:"Mitoz-Mayoz - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b09", name:"Kalıtım", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b10", name:"Kalıtım - Soru", type:"soru", src:"tytAytBiyoBank", qCount:50 },
      { id:"b11", name:"Ekosistem Ekolojisi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b12", name:"Ekosistem - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b13", name:"Canlılarda Enerji Dönüşümleri", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b14", name:"Enerji Dönüşümleri - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b15", name:"Sindirim-Dolaşım Sistemi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b16", name:"Sindirim-Dolaşım - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b17", name:"Solunum-Boşaltım Sistemi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b18", name:"Solunum-Boşaltım - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b19", name:"Sinir-Endokrin-Duyu Sistemi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b20", name:"Sinir-Endokrin-Duyu - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b21", name:"Destek-Hareket Sistemi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b22", name:"Destek-Hareket - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b23", name:"Üreme Sistemi ve Embriyonik Gelişim", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b24", name:"Üreme-Embriyonik Gelişim - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b25", name:"Komünite ve Popülasyon Ekolojisi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b26", name:"Komünite-Popülasyon - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b27", name:"Bitki Biyolojisi", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b28", name:"Bitki Biyolojisi - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 },
      { id:"b29", name:"Genden Proteine", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b30", name:"Genden Proteine - Soru", type:"soru", src:"tytAytBiyoBank", qCount:40 },
      { id:"b31", name:"Madde ve Enerji Akışı", type:"anlatim", src:"aytTytBiyoAnlatim" },
      { id:"b32", name:"Madde-Enerji Akışı - Soru", type:"soru", src:"tytAytBiyoBank", qCount:30 }
    ]
  },
  {
    id: "p3",
    label: "Edebiyat/Türkçe & Tarih",
    priority: 3,
    color: "p3",
    weight: 2,
    topics: [
      { id:"t01", name:"Sözcükte Anlam", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"t02", name:"Cümlede Anlam", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"t03", name:"Paragrafta Anlam", type:"soru", src:"tytTurkce4k", qCount:30 },
      { id:"t04", name:"Paragrafta Yapı", type:"soru", src:"tytTurkce4k", qCount:30 },
      { id:"t05", name:"Paragrafta Konu-Başlık-Anlatım Teknikleri", type:"soru", src:"tytTurkce4k", qCount:30 },
      { id:"t06", name:"Ses Bilgisi", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"t07", name:"Yazım Kuralları", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"t08", name:"Noktalama İşaretleri", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"t09", name:"Sözcükte Yapı / Ekler", type:"soru", src:"tytTurkce4k", qCount:30 },
      { id:"t10", name:"Sözcük Türleri (İsim, Sıfat, Zamir)", type:"soru", src:"tytTurkce4k", qCount:30 },
      { id:"t11", name:"Sözcük Türleri (Fiil, Zarf, Edat, Bağlaç)", type:"soru", src:"tytTurkce4k", qCount:30 },
      { id:"t12", name:"Fiilde Çatı", type:"soru", src:"tytTurkceBank", qCount:25 },
      { id:"t13", name:"Cümlenin Ögeleri", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"t14", name:"Cümle Türleri", type:"soru", src:"tytTurkce4k", qCount:25 },
      { id:"t15", name:"Anlatım Bozuklukları", type:"soru", src:"tytTurkceBank", qCount:30 },
      { id:"e01", name:"Edebiyat-Bilim İlişkisi, Güzel Sanatlar", type:"anlatim", src:"none" },
      { id:"e02", name:"Şiir Bilgisi (Ölçü, Uyak, Söz Sanatları)", type:"anlatim", src:"none" },
      { id:"e03", name:"Şiir Bilgisi - Soru", type:"soru", src:"none", qCount:30 },
      { id:"e04", name:"İslamiyet Öncesi Türk Edebiyatı", type:"anlatim", src:"none" },
      { id:"e05", name:"Halk Edebiyatı (Aşık Tarzı, Tekke-Tasavvuf)", type:"anlatim", src:"none" },
      { id:"e06", name:"Divan Edebiyatı", type:"anlatim", src:"none" },
      { id:"e07", name:"Tanzimat Edebiyatı", type:"anlatim", src:"none" },
      { id:"e08", name:"Servet-i Fünun ve Fecr-i Ati", type:"anlatim", src:"none" },
      { id:"e09", name:"Milli Edebiyat", type:"anlatim", src:"none" },
      { id:"e10", name:"Cumhuriyet Dönemi Şiir", type:"anlatim", src:"none" },
      { id:"e11", name:"Cumhuriyet Dönemi Roman-Hikaye", type:"anlatim", src:"none" },
      { id:"e12", name:"Dünya Edebiyatından Akımlar", type:"anlatim", src:"none" },
      { id:"e13", name:"Edebiyat Genel Tekrar - Soru", type:"soru", src:"none", qCount:40 },
      { id:"h01", name:"Tarih ve Zaman", type:"soru", src:"tytAytTarihBank", qCount:20 },
      { id:"h02", name:"İlk ve Orta Çağlarda Türk Dünyası", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h03", name:"İslam Tarihi ve Medeniyeti", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h04", name:"Türk-İslam Devletleri", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h05", name:"Beylikten Devlete (Osmanlı Kuruluş)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h06", name:"Dünya Gücü Osmanlı (Yükselme Dönemi)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h07", name:"Osmanlı Medeniyeti", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h08", name:"Arayış Yılları (Duraklama-Gerileme)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h09", name:"Avrupa ve Osmanlı Diplomasisi (18.yy)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h10", name:"En Uzun Yüzyıl (Osmanlı Çöküş)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h11", name:"20. Yüzyılda Osmanlı Devleti", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h12", name:"I. Dünya Savaşı", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h13", name:"Milli Mücadele - Hazırlık Dönemi", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h14", name:"Kurtuluş Savaşı'nda Cepheler", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h15", name:"Türk İnkılabı (Atatürk İlke ve İnkılapları)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h16", name:"Atatürk Dönemi Türk Dış Politikası", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h17", name:"II. Dünya Savaşı ve Türkiye", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h18", name:"Soğuk Savaş Dönemi", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h19", name:"Yumuşama Dönemi ve Sonrası", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h20", name:"Küreselleşen Dünya (Günümüz)", type:"anlatim", src:"tytAytTarihElKitabi" },
      { id:"h21", name:"Tarih Genel Tekrar - Soru (TYT)", type:"soru", src:"tytAytTarihBank", qCount:40 },
      { id:"h22", name:"Tarih Genel Tekrar - Soru (AYT)", type:"soru", src:"tytAytTarihBank", qCount:40 },
      { id:"h23", name:"Tarih Genel Tekrar - Soru (4K)", type:"soru", src:"tytTarih4k", qCount:40 }
    ]
  },
  {
    id: "p4",
    label: "Coğrafya, Din, Felsefe",
    priority: 4,
    color: "p4",
    weight: 1,
    topics: [
      { id:"c01", name:"Doğa ve İnsan", type:"soru", src:"tytCografyaBank", qCount:20 },
      { id:"c02", name:"Dünya'nın Şekli ve Hareketleri", type:"soru", src:"tytCografyaBank", qCount:25 },
      { id:"c03", name:"Coğrafi Konum", type:"soru", src:"tytCografya4k", qCount:20 },
      { id:"c04", name:"Harita Bilgisi", type:"soru", src:"tytCografyaBank", qCount:25 },
      { id:"c05", name:"Atmosfer ve İklim", type:"soru", src:"tytCografyaBank", qCount:30 },
      { id:"c06", name:"İklim Tipleri", type:"soru", src:"tytCografya4k", qCount:25 },
      { id:"c07", name:"Basınç ve Rüzgarlar", type:"soru", src:"tytCografyaBank", qCount:20 },
      { id:"c08", name:"Nüfus", type:"soru", src:"tytCografyaBank", qCount:25 },
      { id:"c09", name:"Göç", type:"soru", src:"tytCografya4k", qCount:20 },
      { id:"c10", name:"Yerleşme (Şehirler-Kırsal)", type:"soru", src:"tytCografyaBank", qCount:20 },
      { id:"c11", name:"Türkiye'nin Yer Şekilleri", type:"soru", src:"tytCografyaBank", qCount:25 },
      { id:"c12", name:"Ekonomik Faaliyetler (Tarım, Sanayi)", type:"soru", src:"tytCografya4k", qCount:25 },
      { id:"c13", name:"Bölgeler Coğrafyası", type:"soru", src:"tytCografyaBank", qCount:30 },
      { id:"c14", name:"Çevre ve Toplum", type:"soru", src:"tytCografya4k", qCount:20 },
      { id:"d01", name:"Bilgi ve İnanç", type:"anlatim", src:"none" },
      { id:"d02", name:"İslam ve İbadet", type:"anlatim", src:"none" },
      { id:"d03", name:"Gençlik ve Değerler", type:"anlatim", src:"none" },
      { id:"d04", name:"Din ve Hayat - Soru", type:"soru", src:"none", qCount:25 },
      { id:"d05", name:"Anadolu'da İslam", type:"anlatim", src:"none" },
      { id:"d06", name:"Yahudilik ve Hristiyanlık", type:"anlatim", src:"none" },
      { id:"d07", name:"İslam Düşüncesinde Yorumlar (Mezhepler)", type:"anlatim", src:"none" },
      { id:"d08", name:"Güncel Dini Meseleler", type:"anlatim", src:"none" },
      { id:"d09", name:"Hint ve Çin Dinleri", type:"anlatim", src:"none" },
      { id:"ph01", name:"Felsefenin Konusu", type:"anlatim", src:"none" },
      { id:"ph02", name:"Bilgi Felsefesi", type:"anlatim", src:"none" },
      { id:"ph03", name:"Varlık Felsefesi", type:"anlatim", src:"none" },
      { id:"ph04", name:"Ahlak Felsefesi", type:"anlatim", src:"none" },
      { id:"ph05", name:"Din Felsefesi", type:"anlatim", src:"none" },
      { id:"ph06", name:"Siyaset Felsefesi", type:"anlatim", src:"none" },
      { id:"ph07", name:"Bilim Felsefesi", type:"anlatim", src:"none" },
      { id:"ph08", name:"Sanat Felsefesi", type:"anlatim", src:"none" },
      { id:"ph09", name:"İlk Çağ Felsefesi", type:"anlatim", src:"none" },
      { id:"ph10", name:"Orta Çağ Felsefesi", type:"anlatim", src:"none" },
      { id:"ph11", name:"Yeni Çağ Felsefesi", type:"anlatim", src:"none" },
      { id:"ph12", name:"Modern Felsefe (18-19.yy)", type:"anlatim", src:"none" },
      { id:"ph13", name:"Çağdaş Felsefe (20.yy)", type:"anlatim", src:"none" },
      { id:"ph14", name:"Felsefe Genel Tekrar - Soru", type:"soru", src:"none", qCount:30 }
    ]
  }
];

/* Kullanıcının "zaten bildiğini" belirttiği temel konular: tamamlanmış
   sayılır ama hafif bir ileri-tekrar bloğu olarak p1 havuzunun en başına
   eklenir (50 soru çözüldüğü belirtildiği için kısa pekiştirme). */
const ALREADY_KNOWN = [
  { id:"x01", name:"Temel İşlemler — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:20 },
  { id:"x02", name:"Temel Kavramlar — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:20 },
  { id:"x03", name:"Tek-Çift Sayılar — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:15 },
  { id:"x04", name:"Ardışık Sayılar — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:15 },
  { id:"x05", name:"Faktöriyel — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:15 },
  { id:"x06", name:"Bölme / Bölünebilme — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:20 },
  { id:"x07", name:"Asal Çarpanlara Ayırma — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:15 },
  { id:"x08", name:"EBOB-EKOK — İleri Tekrar", type:"soru", src:"tytMat4k", qCount:20 }
];
